#!/bin/bash
# Jürgen Geuter <tante@the-gay-bar.com> 2010
# 
# kill a running desktopcouch and try to restart it
# it doesn't lose any data (well it shouldn't)
# For more info check out
# http://www.freedesktop.org/wiki/Specifications/desktopcouch/Documentation/Troubleshooting

# kill running desktopcouch
killall beam.smp
# kill old ini file
rm ~/.config/desktop-couch/desktop-couchdb.ini
# now try restaring via dbus
dbus-send --session --dest=org.desktopcouch.CouchDB --print-reply --type=method_call / org.desktopcouch.CouchDB.getPort

